title: Mega Drive / Genesis Mini Compatibility List
theme: jekyll-theme-slate
show_downloads: false
licensed: https://megadrive-compatibility.netlify.app
unlicensed: unlicensed.html
betas: betas.html
translations: translations.html
hacks: hacks.html
paltontsc: paltontsc.html